### PR TITLE
Italian translation for WinBox-Reloaded

### PR DESCRIPTION
**Pull request by explorerdotexe**
This is an Italian translation for WinBox-Reloaded. It includes Italian text and messages for all text in WinBox-Reloaded. It is mostly confirmed working, the only thing that doesn't work on my end as of this pull request is the New Virtual Hard Disk Wizard, which freezes the program upon opening.
This language file can be tested out by changing the extension from ".it-IT" to ".en-US" and replacing the existing "Language.en-US" file within the Languages folder of your WinBox installation. (Your language settings must be set to English for this to work)

Screenshots:
image
image
image
image
image

### CODE REVIEW

**Comment by laciba96** [comment]
Fantastic work, it looks so nicely, thank you. I merge it immediately.

I'll surely add it to the releases after the grand rework. I don't want to apply big changes to the UI, so it probably could be used many later versions too without any change.

**Comment by laciba96** [comment]
Also I mention in the README.md file, that Italian translation is available, and how could it applied to existing versions.

**Comment by laciba96** [comment]
I think I found what causes the freeze, there's a single backslash in line 280 (Label27=..). I don't know Italian, so I don't know that this sign is really needed, or just accidental, but assuming the first option I modified it to `\\`. 

This is needed because the lines are [C-style escaped strings](https://en.wikipedia.org/wiki/Escape_sequences_in_C), and \r \n for example special characters (that means Enter). If you want to type \ into the text, you have to type` \\`. Now the Virtual Hard Disk dialog works flawlessly, and the dialogs looks awesome in Italian. 

kép

Note: You can override the program display language by using the "-lang it-IT" parameter. This is how I tested it, and it could be useful for later. In the future I want to make a guide for these things at the Wiki site, where I mention these stuff.

**Comment by explorerdotexe** [comment]
> 
> 
> I think I found what causes the freeze, there's a single backslash in line 280 (Label27=..). I don't know Italian, so I don't know that this sign is really needed, or just accidental, but assuming the first option I modified it to `\\`.
> 
> This is needed because the lines are [C-style escaped strings](https://en.wikipedia.org/wiki/Escape_sequences_in_C), and \r \n for example special characters (that means Enter). If you want to type \ into the text, you have to type` \\`. Now the Virtual Hard Disk dialog works flawlessly, and the dialogs looks awesome in Italian.
> 
> kép
> 
> Note: You can override the program display language by using the "-lang it-IT" parameter. This is how I tested it, and it could be useful for later. In the future I want to make a guide for these things at the Wiki site, where I mention these stuff.

Ah, that likely got deleted accidentally while i was editing the file in Notepad++. Anyways, I'm glad you liked it so much. can't wait to see this fully integrated in the grand rework.

**Comment by explorerdotexe** [comment]
One small issue with the fixed translation, it seems that the disk wizard displays this backslash in the bottom text, when it should be hidden. Aside from that, everything else seems to display correctly.
image

**Comment by laciba96** [comment]
It can be removed of course. I didn't know that this sign in text is intentional or accidental, but of course I can remove if it's unnecessary.

**Comment by explorerdotexe** [comment]
> 
> 
> It can be removed of course. I didn't know that this sign in text is intentional or accidental, but of course I can remove if it's unnecessary.
> 
> Ps.: The backslash is removed in my last commit to main.

Tried it now, it displays without the backslash and doesn't crash. Aside from a minor double space in line 436, it should now be finalized.

**Comment by laciba96** [comment]
Thank you for the help and for the checks, the double space in line 436 also fixed. (latest commit)

**Pull request merged**
